### ISSUE TITLE
XML Sitemap Unit Tests

### ISSUE THREAD

**Issue by alexfinnarn** [backdrop-contrib/xmlsitemap#29] opened 2016-12-03 20:29 UTC
92 passes, 11 fails, 1 exception, and 5 debug messages

All seems to relate to Regenerate flag. I had issues with that variable before so this doesn't surprise me.

**Comment by alexfinnarn** [comment] 2016-12-27 21:03
The last few failed tests relate to the regenerate flag during a cron run: Issue #32.

However, testSaveLink() includes a lot of failures also related to the regenerate flag not being reset. The curious thing is that if you place an assertion before the first link is saved,

`  function testSaveLink() {
    $this->assertFlag('regenerate_needed', TRUE);
    $link = array('type' => 'testing', 'id' => 1, 'loc' => 'testing', 'status' => 1);
    xmlsitemap_link_save($link);
    $this->assertFlag('regenerate_needed', TRUE);`

the first assertion passes but the second assertion fails. Leaving the test as it was...

`  function testSaveLink() {
    $link = array('type' => 'testing', 'id' => 1, 'loc' => 'testing', 'status' => 1);
    xmlsitemap_link_save($link);
    $this->assertFlag('regenerate_needed', TRUE);`

causes the assertion after the link is saved to pass. Wahht? How can asserting if a variable is set to TRUE interfere with the second assertion?

This makes me think something is screwy with accessing variables during tests runs...or the process after a link is saved takes too long for the assertion to pass...don't understand it. 

The good news is that while manually testing adding a page, unpublishing, and republishing it, the sitemap is set to be regenerated.

**Comment by quicksketch** [comment] 2022-08-03 21:42
Thanks @alexfinnarn! I dug through these errors and it looks like these failures were simply caused by the state variable being named `xmlsitemap_regenerate_needed`, not `regenerate_needed`. This has been fixed in https://github.com/backdrop-contrib/xmlsitemap/pull/107.

**Closed** 2022-08-03 21:44 UTC
